apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: php-app
type: Opaque
stringData:
#for MySQL container
    MYSQL_DATABASE: mydb
    MYSQL_USER: phpuser
    MYSQL_PASSWORD: password
    MYSQL_ROOT_PASSWORD: rootpassword

#for PHP application container
    DB_HOST: mysql-service
    DB_NAME: mydb
    DB_USER: phpuser
    DB_PASSWORD: password

